- name: Certificates create
  hosts: all
  gather_facts: false
  vars:
    certificates_kubernetes_cluster:
      domain: kubernetes.local
      endpoint: server
  roles:
    - certificates

- name: Basic setup
  hosts:
    - servers
    - workers
  gather_facts: false
  vars:
    server_hosts:
      - 192.168.56.10 server.kubernetes.local
  roles:
    - server

- name: Install etcd
  hosts:
    - etcd
  gather_facts: false
  roles:
    - etcd
