# Check variables
- name: Server | host | assert server_hosts format
  ansible.builtin.assert:
    that:
      - item is match('^([0-9]{1,3}\.){3}[0-9]{1,3} [a-zA-Z0-9.-]+$')
    msg: "Invalid entry: {{ item }}. Must be '<IP> <hostname>'."
  loop: "{{ server_hosts }}"

# /etc/host file
- name: Server | host | get all hosts variables
  ansible.builtin.set_fact:
    server_included_groups: "{{ groups.keys() | difference(['all', 'ungrouped']) }}"

- name: Server | host | set hostname
  ansible.builtin.hostname:
    name: "{{ server_hostname }}"

- name: Server | host | update /etc/hosts file
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: >
      {{ hostvars[item].server_ip }}
      {{ hostvars[item].server_hostname | default(inventory_hostname) }}
      {% if hostvars[item].server_domain is defined -%}
      {{ hostvars[item].server_hostname | default(inventory_hostname) }}.{{ hostvars[item].server_domain }}
      {% endif %}
    marker: "# --- {mark} ANSIBLE --- {{ item }}"
  loop: "{{ server_included_groups | map('extract', groups) | flatten }}"
  when: hostvars[item].server_ip is defined

- name: Server | host | update /etc/hosts file from variable
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: "{{ item }}"
  loop: "{{ server_hosts | default([]) }}"
